parameters:
  - name: project
  - name: environment
  - name: service_connection

stages:
  - stage: helm
    displayName: Helm
    jobs:
      - job: helm
        displayName: Helm
        workspace:
          clean: all
        steps:
          - task: AzureCLI@2
            displayName: Helm
            inputs:
              azureSubscription: ${{ parameters.service_connection }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
              addSpnToEnvironment: true
