variables:
  - group: aks-dev

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - applications/**/*
      - helm/**/*
      - modules/**/*
      - pipelines/**/*
      - scripts/**/*
      - terraform/**/*
    include:
      - pipelines/aks.yml
      - pipelines/templates/helm.yml
      - scripts/helm.sh

stages:
  - template: ./templates/helm.yml
    parameters:
      service_connection: $(service_connection)
      aks_connection:     $(aks_connection)
      environment:        $(environment)
      project:            $(project)