pool:
  vmImage: ubuntu-latest

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - helm/**/*
      - modules/**/*
      - pipelines/**/*
      - scripts/**/*
      - terraform/**/*
    include:
      - applications/books
      - pipelines/books.yml

variables:
  - name: buildId
    value: $[ counter('1.0') ]
stages:
  - stage: docker
    jobs:
      - job: docker
        workspace:
          clean: all
        steps:
          - script: |
              # update the pipeline build number
              echo "##vso[build.updatebuildnumber]1.0.$(buildId)"
            condition: always()
            displayName: update build number

          - bash: |
              docker --version
            displayName: docker version

          - task: replacetokens@6
            inputs:
              sources: applications/books/index.js

          - task: Docker@2
            displayName: Login to hub.docker.com
            inputs:
              command: login
              containerRegistry: hub.docker.com

          - task: Docker@2
            displayName: Build and Push
            env:
              DOCKER_BUILDKIT: 1
            inputs:
              command: buildAndPush
              repository: leriksen/books # username/contosoRepository for DockerHub
              buildContext: applications/books
              tags: |
                $(Build.BuildNumber)
                latest