variables:
  - group: terraform-base
  - group: devops-base
  - group: devops-non-prod
  - group: devops-dev

pool:
  vmImage: ubuntu-22.04

trigger:
  batch: true
  branches:
    include:
      - master
      - main
  paths:
    exclude:
      - pipelines/aks.yml
      - pipelines/templates/helm.yml
      - scripts/helm.sh

stages:
  - template: ./templates/plan.yml
    parameters:
      sa:                 $(sa)
      container:          $(container)
      service_connection: $(service_connection)
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      pod1secret:         $(pod1secret)
      pod2secret:         $(pod2secret)

  - template: ./templates/apply.yml
    parameters:
      sa:                 $(sa)
      container:          $(container)
      service_connection: $(service_connection)
      environment:        $(environment)
      project:            $(project)
      subscription_id:    $(subscription_id)
      pod1secret:         $(pod1secret)
      pod2secret:         $(pod2secret)
