apiVersion: v1
kind: ConfigMap
metadata:
  name: book-config
data:
  PORT:      "{{ .Values.pod.image_port }}"
  DATA_PATH: "{{ .Values.pod.data_path  }}"
  FROM_HELM: "{{ .Values.static.prove_helm }}"
