apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "books.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- with .Values.selectorLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- with .Values.labels.pod }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.pod.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: book-config

