apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: leriksen/books:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /data/books
              name: local-sc-pvc
      volumes:
        - name: local-sc-pvc
          persistentVolumeClaim:
            claimName: local-sc-pvc
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000