apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sc-pv
  labels:
    type: local
spec:
  storageClassName: local-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/data

