apiVersion: v1
kind: Service
metadata:
  name: books-svc
  labels:
    app: books
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.selectorLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
