kind: Deployment
apiVersion: apps/v1
metadata:
  name: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
        - name: books
          image: leriksen/books:latest
          ports:
            - containerPort: 3000